### ISSUE TITLE
Add Getting-started to README

### ISSUE THREAD

**Issue by 153957** [bitmovin/bitmovin-python#66]
The steps to get started available once logged in on are very helpful:
https://dashboard.bitmovin.com/getting-started/encoding/python/1
Could you add those steps to the README, or at least link to them?
Or also make them available without requiring an account.

**Comment by lukaskroepfl** [comment]
Hi @153957!
Thank you for your feedback, we released the getting started guide just a few days ago and are working on updating all API client READMEs to link to the guide.
