### ISSUE TITLE
Errors in Getting-started guide

### ISSUE THREAD

**Issue by 153957** [bitmovin/bitmovin-python#67]
In the step 'Reuse Inputs' a '.get' is used to get an existing input, however that method does not exist:

```python
>>> bitmovin.inputs.HTTPS.get('my-input-id').resource
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'HTTPS' object has no attribute 'get'
```

The RestService has no `get` method, but does have `retrieve`:
https://github.com/bitmovin/bitmovin-python/blob/master/bitmovin/services/rest_service.py#L47

So it should be `.retrieve`:
```python
>>> bitmovin.inputs.HTTPS.retrieve('my-input-id').resource
<bitmovin.resources.models.inputs.https_input.HTTPSInput object at 0x0abcdefghi>
```
https://dashboard.bitmovin.com/getting-started/encoding/python/3

This probably applies to output and encoding as well.

**Comment by lukaskroepfl** [comment]
Hey! Thanks for reporting, should be fixed. 👍

**Comment by 153957** [comment]
Thanks, Looks good to me!
