### ISSUE TITLE
Missing audio muxing stream in Getting Started guide

### ISSUE THREAD

**Issue by 153957** [bitmovin/bitmovin-python#68]
On: https://dashboard.bitmovin.com/getting-started/encoding/python/6

In the Audio Muxing section the `audio_muxing_stream` variable is not created.

This line should be included:
`audio_muxing_stream = MuxingStream(audio_stream.id)`

**Comment by lukaskroepfl** [comment]
You are correct, I will push a fix shortly.
Did you check out the full python example available for download [here](https://dashboard.bitmovin.com/getting-started/encoding/python/1)?

**Comment by 153957** [comment]
Yes, but I need a much less complex configuration and the getting-started guide keeps it more to the point. I just finished my configuration/script, I will shortly be testing it.

**Comment by lukaskroepfl** [comment]
I see, the audio muxing stream fix has been pushed and should be available.
