### ISSUE TITLE
Support all CloudRegions

### ISSUE THREAD

**Issue by 153957** [bitmovin/bitmovin-python#70]
Please add the following list of supported cloud regions to the [CloudRegion](https://github.com/bitmovin/bitmovin-python/blob/master/bitmovin/resources/enums/cloud_region.py) enum:
```
GOOGLE_US_WEST_1
AZURE_EUROPE_WEST
NORTH_AMERICA
SOUTH_AMERICA
EUROPE
AFRICA
ASIA
AUSTRALIA
AWS
GOOGLE
AUTO
```
Taken from:
https://bitmovin.com/encoding-documentation/bitmovin-api/#/reference/encoding/filters/create-encoding -> cloudRegion

**Comment by dominic-miglar** [comment]
Added missing cloud regions in https://github.com/bitmovin/bitmovin-python/releases/tag/v1.23.0
