### ISSUE TITLE
wait_until_finished timeout

### ISSUE THREAD

**Issue by vkvam** [bitmovin/bitmovin-python#74]
When for some reason an encoding or other operation can not be completed, a timeout parameter in wait_until_finished methods would be very useful.

**Comment by dominic-miglar** [comment]
Added support for this in https://github.com/bitmovin/bitmovin-python/releases/tag/v1.23.0. It's now possible to specify a timeout in seconds.

```Python
....
bitmovin.encodings.Encoding.wait_until_finished(encoding_id=encoding.id, timeout=3600*2)
....
bitmovin.manifests.DASH.wait_until_finished(manifest_id=dash_manifest.id, timeout=3600*2)
....
```
